# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "ru_bee", "~> 0.1.1"

gem "rword", "~> 1.1"

gem "tty-prompt", "~> 0.23.1"

gem "word_wrap", "~> 1.0"

gem "nokogiri", "~> 1.6"

gem "pastel", "~> 0.8.0"

gem "timeout", "~> 0.2.0"

gem "tty-progressbar", "~> 0.18.2"

gem "artii", "~> 2.1"

gem "rspec", "~> 3.11"
